### ISSUE TITLE
how to obtain a good result?

### ISSUE THREAD

**Issue by Engro39** [MarcioCerqueira/RealTimeSpecularHighlightRemoval#3]
Thank you for sharing your code. I think the shadow removal is one of the most challenge works in vision field. 

Based on your code, I am trying to solve my problems

**input image**
![image](https://user-images.githubusercontent.com/13134640/56231979-b8c24b00-604d-11e9-81c9-87ddb3bb228f.png)

**output image**
![image](https://user-images.githubusercontent.com/13134640/56231987-beb82c00-604d-11e9-85d4-2b242bec749d.png)

As you can see, the road area is gone and the shadow still exists. How can I improve the result? Could you advise me?

**Comment by MarcioCerqueira** [comment]
Hello @ChulhoonJang,

Thank you for your interest in our source code.

I do agree with you that shadow removal is quite an interesting and challenging problem in computer vision. However, I believe that I am missing some essential step towards adapting this source code to solve the task of shadow removal. Looking solely at the image, it is not clear (for me) what is wrong with your proposal. I would need to know more details about your algorithm or your idea in order to give you better advices on this subject. 

We can have a private discussion about this issue via e-mail, if you want.

**Comment by ChulhoonJang** [comment]
Thank you for your reply, @MarcioCerqueira. I just ran your code for the example image and got the output image.
